export const PERMISSIONS = [
  { code: "dashboard.read", name: "View dashboard", module: "dashboard" },
  { code: "employees.read", name: "View employees", module: "employees" },
  { code: "employees.write", name: "Manage employees", module: "employees" },
  { code: "employees.delete", name: "Delete employees", module: "employees" },
  { code: "departments.read", name: "View departments", module: "departments" },
  { code: "departments.write", name: "Manage departments", module: "departments" },
  { code: "tasks.read", name: "View tasks", module: "tasks" },
  { code: "tasks.write", name: "Manage tasks", module: "tasks" },
  { code: "meetings.read", name: "View meetings", module: "meetings" },
  { code: "meetings.write", name: "Manage meetings", module: "meetings" },
  { code: "assets.read", name: "View assets", module: "assets" },
  { code: "assets.write", name: "Manage assets", module: "assets" },
  { code: "documents.read", name: "View documents", module: "documents" },
  { code: "documents.write", name: "Manage documents", module: "documents" },
  { code: "announcements.read", name: "View announcements", module: "announcements" },
  { code: "announcements.write", name: "Manage announcements", module: "announcements" },
  { code: "messages.read", name: "View messages", module: "messages" },
  { code: "messages.write", name: "Send messages", module: "messages" },
  { code: "calendar.read", name: "View calendar", module: "calendar" },
  { code: "calendar.write", name: "Manage calendar", module: "calendar" },
  { code: "reports.read", name: "View reports", module: "reports" },
  { code: "integrations.read", name: "View integrations", module: "integrations" },
  { code: "integrations.write", name: "Manage integrations", module: "integrations" },
  { code: "settings.read", name: "View settings", module: "settings" },
  { code: "settings.write", name: "Manage settings", module: "settings" },
  { code: "roles.write", name: "Manage roles", module: "settings" },
  { code: "audit.read", name: "View audit logs", module: "settings" },
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number]["code"];

export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  Administrator: PERMISSIONS.map((p) => p.code),
  "Office Manager": [
    "dashboard.read",
    "employees.read",
    "employees.write",
    "departments.read",
    "departments.write",
    "tasks.read",
    "tasks.write",
    "meetings.read",
    "meetings.write",
    "assets.read",
    "assets.write",
    "documents.read",
    "documents.write",
    "announcements.read",
    "announcements.write",
    "messages.read",
    "messages.write",
    "calendar.read",
    "calendar.write",
    "reports.read",
    "integrations.read",
    "integrations.write",
    "settings.read",
  ],
  "Department Manager": [
    "dashboard.read",
    "employees.read",
    "departments.read",
    "tasks.read",
    "tasks.write",
    "meetings.read",
    "meetings.write",
    "assets.read",
    "documents.read",
    "announcements.read",
    "messages.read",
    "messages.write",
    "calendar.read",
    "reports.read",
    "integrations.read",
  ],
  Employee: [
    "dashboard.read",
    "employees.read",
    "departments.read",
    "tasks.read",
    "meetings.read",
    "assets.read",
    "documents.read",
    "announcements.read",
    "messages.read",
    "messages.write",
    "calendar.read",
    "reports.read",
    "integrations.read",
  ],
};
